models Review and Comment
d2avids/api_yamdb pull request #29
Opened 2023-06-29 21:02 UTC by Pletennyy

2023-06-29 21:10 UTC, Pletennyy commented
Модели Review и Comment

2023-06-30 12:05 UTC, Dimitresku commented on api_yamdb/reviews/models.py
> +class Review(models.Model):
Предлагаю моделям везде добавить докстринги, чтобы была консистентность кода)

2023-06-30 12:14 UTC, Dimitresku commented on api_yamdb/reviews/models.py
> +        verbose_name='Рейтинг',
В redoc score - это оценка. Рейтинг, я так понимаю, из всех оценок составляется. Поправь пожалуйста)

2023-06-30 12:14 UTC, Dimitresku commented on api_yamdb/reviews/models.py
> +        validators=[
лайк

2023-06-30 12:15 UTC, Dimitresku commented on api_yamdb/reviews/models.py
> +        constraints = [
Эта проверка на уникалность отзыва в модели лайк однозначно!

2023-06-30 12:18 UTC, Dimitresku commented on api_yamdb/reviews/models.py
> +class Comment(models.Model):
Докстринг бы)

2023-06-30 12:20 UTC, Dimitresku commented on api_yamdb/reviews/models.py
> +        verbose_name='Пользователь',
Тут я бы для понимания обозвал автора не пользователь, а автор комментария)

2023-06-30 12:22 UTC, Dimitresku reviewed
В целом хорошо постарался!
Подправь, пожалуйста, места с моими комментариями.

2023-06-30 12:37 UTC, d2avids requested changes
Отлично, только небольшие правки перед мержем

2023-06-30 12:37 UTC, d2avids commented on api_yamdb/reviews/models.py
> +        verbose_name='Рейтинг',
из пользовательских оценок формируется усреднённая оценка произведения — рейтинг (целое число). На одно произведение пользователь может оставить только один отзыв.

2023-07-01 06:00 UTC, Pletennyy commented
Запушил. Про оценку и рейтинг полностью согласен.

2023-07-01 08:16 UTC, merged