Сделаны все модели, вью, урлы и сериалайзеры
d2avids/api_yamdb pull request #31
Opened 2023-06-30 16:20 UTC by Dimitresku

1.Модели вроде готовы, осталось доработать связующую модель(займусь этим вместе с данными csv)
2.Урлы подключены к вью сетам.
3.Вью сеты тоже почти сделаны, осталось пермишны подключить для разных запросов и сделать фильтрацию для произведений.
4. Сериализатор произведения до конца не продумал еще + докстринги у них забыл)

2023-06-30 23:00 UTC, d2avids approved these changes
Дмитрий, молодец! Все очень круто! Что править не нашел, зато вспомнил, что нужно зарегистрировать модели в админке и на твоем примере понял, как проводить валидацию по Regex.
Правда, я удалил миграции, чтобы избавиться от конфликтов. В дальнейшем предлагаю миграции не коммитить, а проводить локально, чтобы не мучаться с ними.

EDIT: Через 40 минут обратил внимание на документацию и ниже оставил комментарий по поводу доступности методов к эндпоинтам. Обрати внимание)

2023-07-01 00:10 UTC, d2avids requested changes
Чуть позднее заметил одну недоработку касающуюся доступности различных эндпоинтов к ресурсам. Оставил коммент в urls.py

2023-07-01 00:10 UTC, d2avids commented on api_yamdb/api/urls.py
> +router_v1.register("v1/categories", CategoryViewSet, basename="category")
Если я верно все понял, то по всем путям у тебя доступны все методы. Надо ограничить методы для жанров, произведений и категорий. Согласно редок, жанры и категории имеют только методы get list, post и del. Title имеет все, кроме Put. можно пробовать через изменение вьюсетов (миксины), а можно как по моему примеру в пулл реквесте с юзерами в этом же файле

2023-07-01 09:32 UTC, Dimitresku commented on api_yamdb/api/views.py
> +
Да, нужно почитать доки про фильтерсет.

2023-07-03 19:14 UTC, Dimitresku reviewed
0.Сделал разрешенные методы запросов для вьюсетов title, genre & category
1.Пока закомментил permission, чтобы после слияния с dev проверить их работу.
2.Миграции удалил перед пушем.
3.Вопрос, нужна ли пагинация?

2023-07-04 13:36 UTC, d2avids reviewed
немного пермишены переделать, а так все супер

2023-07-04 13:36 UTC, d2avids commented on api_yamdb/api/views.py
> +    #     IsAdminOrReadOnly,
будет конфликтовать, да и лучше просто IsAdmin

2023-07-04 13:36 UTC, d2avids commented on api_yamdb/api/views.py
> +    # permission_classes = (IsAdminOrReadOnly, IsModerator)
IsAdminOrReadOnly отлично подходит, IsModerator не нужен, согласно доке

2023-07-04 13:36 UTC, d2avids commented on api_yamdb/api/views.py
> +    # permission_classes = (IsAdminOrReadOnly, IsModerator)
то же, что и с жанрами

2023-07-04 13:36 UTC, d2avids commented on api_yamdb/api/views.py
> +        raise MethodNotAllowed('GET')
отлично, потом проверим, пропускает ли такое Pytest

2023-07-04 13:36 UTC, d2avids commented on api_yamdb/reviews/admin.py
> +class TitleAdmin(admin.ModelAdmin):
бомба

2023-07-04 14:47 UTC, merged